name: 'Setup Environment'
description: 'Sets up environment variables for MFEM sanitizer workflow'
inputs:

  DEBUG:
    type: string
    default: 'true'
    required: false

  LSAN_DIR:
    description: 'LSAN suppression directory'
    required: false
    type: string
    default: 'lsan'

  LSAN_FILE:
    description: 'LSAN suppression file'
    required: false
    type: string
    default: 'lsan.supp'

  CLANG_VER:
    description: 'CLANG version to use'
    required: false
    type: number
    default: 18

  LLVM_VER:
    description: 'LLVM version to use'
    required: false
    type: string
    default: '19.1.7'

  HYPRE_VER:
    description: 'HYPRE version to build'
    required: false
    type: string
    default: '2.19.0'

  METIS_VER:
    description: 'METIS version to build'
    required: false
    type: string
    default: '4.0.3'

runs:
  using: 'composite'
  steps:
    - name: Env (Inputs)
      run: |
        echo DEBUG=${{inputs.DEBUG}} >> $GITHUB_ENV
        echo LSAN_DIR=${{inputs.LSAN_DIR}} >> $GITHUB_ENV
        echo LLVM_VER=${{inputs.LLVM_VER}} >> $GITHUB_ENV
        echo LSAN_FILE=${{inputs.LSAN_FILE}} >> $GITHUB_ENV
        echo CLANG_VER=${{inputs.CLANG_VER}} >> $GITHUB_ENV
        echo HYPRE_VER=${{inputs.HYPRE_VER}} >> $GITHUB_ENV
        echo METIS_VER=${{inputs.METIS_VER}} >> $GITHUB_ENV
      shell: bash

    - name: Env (dir)
      run: |
        echo LLVM_DIR=${{github.workspace}}/llvm >> $GITHUB_ENV
        echo HYPRE_DIR=hypre-${{inputs.HYPRE_VER}} >> $GITHUB_ENV
        echo METIS_DIR=metis-${{inputs.METIS_VER}} >> $GITHUB_ENV
      shell: bash

    - name: Env (bis)
      run: |
        echo CC=clang-${{inputs.CLANG_VER}} >> $GITHUB_ENV
        echo CXX=clang++-${{inputs.CLANG_VER}} >> $GITHUB_ENV
        echo LLVM_INC=${{env.LLVM_DIR}}/include/c++/v1 >> $GITHUB_ENV
        echo LLVM_LIB=${{env.LLVM_DIR}}/lib >> $GITHUB_ENV
        echo HYPRE_TGZ=v${{inputs.HYPRE_VER}}.tar.gz >> $GITHUB_ENV
        echo METIS_TGZ=metis-${{inputs.METIS_VER}}.tar.gz >> $GITHUB_ENV
        echo LSAN_OPTIONS=suppressions=${{github.workspace}}/${{inputs.LSAN_DIR}}/${{inputs.LSAN_FILE}} >> $GITHUB_ENV
      shell: bash

    - name: Env (ter)
      run: |
        echo LLVM_CXXFLAGS=-stdlib=libc++ -I${{env.LLVM_INC}} -Isystem${{env.LLVM_INC}} >> $GITHUB_ENV
        echo LLVM_LDFLAGS=-L${{env.LLVM_LIB}} -lc++abi -Wl,-rpath,${{env.LLVM_LIB}} >> $GITHUB_ENV
      shell: bash
  
    - name: Echo
      run: |
        echo "[LLVM_DIR] ${{ env.LLVM_DIR }}"
        echo "[HYPRE_DIR] ${{ env.HYPRE_DIR }}"
        echo "[METIS_DIR] ${{ env.METIS_DIR }}"
        echo "[CC] ${{ env.CC }}"
        echo "[CXX] ${{ env.CXX }}"
        echo "[LLVM_INC] ${{ env.LLVM_INC }}"
        echo "[LLVM_LIB] ${{ env.LLVM_LIB }}"
        echo "[HYPRE_TGZ] ${{ env.HYPRE_TGZ }}"
        echo "[METIS_TGZ] ${{ env.METIS_TGZ }}"
        echo "[LSAN_OPTIONS] ${{ env.LSAN_OPTIONS }}"
        echo "[LLVM_CXXFLAGS] ${{env.LLVM_CXXFLAGS}}"
        echo "[LLVM_LDFLAGS] ${{env.LLVM_LDFLAGS}}"
      shell: bash
  