name: build-hypre

on:
  workflow_call:
    inputs:
      HYPRE_VER:
        description: 'HYPRE version to build'
        required: false
        type: string
        default: '2.19.0'

  #############
  # Build HYPRE
  # Cache: ${{runner.os}}-ompi-build-${{env.HYPRE_DIR}}-int32-fp64-v2.5
jobs:
  build-hypre:
    runs-on: ubuntu-latest
    name: build-hypre
    steps:
      - name: Env
        run: |
          echo "HYPRE_DIR=hypre-${{inputs.HYPRE_VER}}" >> $GITHUB_ENV
          echo "HYPRE_TGZ=v${{inputs.HYPRE_VER}}.tar.gz" >> $GITHUB_ENV
      - name: Cache
        id: cache
        uses: actions/cache@v4
        with:
          path: ${{env.HYPRE_DIR}}
          key: ${{runner.os}}-ompi-build-${{env.HYPRE_DIR}}-int32-fp64-v2.5
      - name: Setup
        if: steps.cache.outputs.cache-hit != 'true'
        run: sudo apt-get install openmpi-bin libopenmpi-dev
      - name: Build
        if: steps.cache.outputs.cache-hit != 'true'
        uses: mfem/github-actions/build-hypre@v2.5
        with:
          archive: ${{env.HYPRE_TGZ}}
          dir: ${{env.HYPRE_DIR}}
          target: int32
          precision: fp64
          build-system: make
