name: build-mfem-par

on:
  workflow_call:

#####################
# Build MFEM Parallel
# Cache:   cache-mfem-par-${{matrix.sanitizer}}
# Upload: upload-mfem-par-${{matrix.sanitizer}}
jobs:
  build-par-mfem:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        sanitizer: [asan, ubsan]
        include:
          - sanitizer: asan
            cxxflags: "-fsanitize=address -fsanitize-address-use-after-scope"
            ldflags: "-fsanitize=address"
          - sanitizer: ubsan
            cxxflags: "-fsanitize=undefined"
            ldflags: "-fsanitize=undefined"
    name: ${{matrix.sanitizer}}
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/sanitize/env
      
      - uses: ./.github/actions/sanitize/mpi

      - name: mfem
        uses: ./.github/actions/sanitize/mfem
        with:
          key: mfem-par-${{matrix.sanitizer}}
          par: true