---
name: "Sanitizers"

permissions:
  actions: write

on:
  # Run on pushes to main development branches
  push:
    branches: ["main"]
  # Run on all pull requests
  pull_request: 
  # Allow manual triggering for debugging
  workflow_dispatch:

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  build-seq-mfem:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sanitizer: [asan, msan, ubsan]
    name: build-seq-${{matrix.sanitizer}}
    steps:
      - name: Touch build-seq-${{matrix.sanitizer}}
        run:  touch build-seq-${{matrix.sanitizer}}
      - name: Cache
        uses: actions/cache@v4
        with:
          path: cache 
          key:  cache-build-seq-${{matrix.sanitizer}}-${{github.sha}}

  build-par-mfem:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sanitizer: [asan, msan, ubsan]
    name: build-${{matrix.sanitizer}}-par
    steps:
      - name: Touch build-par-${{matrix.sanitizer}}
        run:  touch build-par-${{matrix.sanitizer}}
      - name: Cache
        uses: actions/cache@v4
        with:
          path: cache 
          key:  cache-build-par-${{matrix.sanitizer}}-${{github.sha}}

  build-par-hypre:
    runs-on: ubuntu-latest
    name: build-par-hypre
    steps:
      - name: Run build Hypre
        run: |
          echo Running build Hypre

  build-par-metis:
    runs-on: ubuntu-latest
    name: build-par-metis
    steps:
      - name: Run build Metis
        run: |
          echo Running build Metis

  test-seq:
    needs: [build-seq-mfem]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sanitizer: [asan, msan, ubsan]
        test: [examples, miniapps, tests]
    name: test-seq-${{matrix.sanitizer}}-${{matrix.test}}
    steps:
      - name: Restore
        uses: actions/cache@v4
        with:
          path: cache
          key:  cache-build-seq-${{matrix.sanitizer}}-${{github.sha}}

      - name: Run ${{ matrix.test }}
        run: |
          echo Running ${{ matrix.test }}

  test-par:
    needs: [build-par-mfem, build-par-hypre, build-par-metis]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sanitizer: [asan, msan, ubsan]
        test: [examples, miniapps, tests]
    name: test-par-${{matrix.sanitizer}}-${{matrix.test}}
    steps:
      - name: Restore
        uses: actions/cache@v4
        with:
          path: cache
          key:  cache-build-par-${{matrix.sanitizer}}-${{github.sha}}

      - name: Run ${{ matrix.test }}
        run: |
          echo Running ${{ matrix.test }}
