---
name: "Sanitizers"

permissions:
  actions: write

on:
  # Run on pushes to main development branches
  push:
    branches: ["main"]
  # Run on all pull requests
  pull_request: 
  # Allow manual triggering for debugging
  workflow_dispatch:

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  build-mfem-seq:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sanitizer: [asan, msan, ubsan]
    name: build-${{matrix.sanitizer}}-seq
    steps:
      - name: Touch build-${{matrix.sanitizer}}-seq
        run:  touch build-${{matrix.sanitizer}}-seq
      - name: Cache
        uses: actions/cache@v4
        with:
          path: cache 
          key:  cache-build-${{matrix.sanitizer}}-seq-${{github.sha}}

  build-mfem-par:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sanitizer: [asan, msan, ubsan]
    name: build-${{matrix.sanitizer}}-par
    steps:
      - name: Touch build-${{matrix.sanitizer}}-par
        run:  touch build-${{matrix.sanitizer}}-par
      - name: Cache
        uses: actions/cache@v4
        with:
          path: cache 
          key:  cache-build-${{matrix.sanitizer}}-par-${{github.sha}}

  build-hypre:
    runs-on: ubuntu-latest
    name: build-hypre
    steps:
      - name: Run build Hypre
        run: |
          echo Running build Hypre

  build-metis:
    runs-on: ubuntu-latest
    name: build-metis
    steps:
      - name: Run build Metis
        run: |
          echo Running build Metis

  test-seq:
    needs: [build-mfem-seq]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sanitizer: [asan, msan, ubsan]
        test: [examples, miniapps, tests]
    name: test-${{matrix.sanitizer}}-seq-${{matrix.test}}
    steps:
      - name: Restore
        uses: actions/cache@v4
        with:
          path: cache
          key:  cache-build-${{matrix.sanitizer}}-seq-${{github.sha}}

      - name: Run ${{ matrix.test }}
        run: |
          echo Running ${{ matrix.test }}

  test-par:
    needs: [build-mfem, build-hypre, build-metis]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sanitizer: [asan, msan, ubsan]
        test: [examples, miniapps, tests]
    name: test-${{matrix.sanitizer}}-par-${{matrix.test}}
    steps:
      - name: Restore
        uses: actions/cache@v4
        with:
          path: cache
          key:  cache-build-${{matrix.sanitizer}}-par-${{github.sha}}

      - name: Run ${{ matrix.test }}
        run: |
          echo Running ${{ matrix.test }}
