name: test-par-check
on:
  workflow_call:
jobs:
  test-par-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sanitizer: [asan, ubsan]
    name: ${{matrix.sanitizer}} 
    steps:
      - uses: actions/checkout@v4
      - name: Restore
        id: restore
        uses: ./.github/actions/sanitize/restore
        with:
          cache-path: mfem/build/examples/ex1p
          cache-key: check-par-${{matrix.sanitizer}}
          build-key: mfem-par-${{matrix.sanitizer}}
          par: true
      - name: MFEM Check
        if: ${{ steps.restore.outputs.cache-hit != 'true' }}
        working-directory: mfem/build
        run: ninja -v check