name: build-file-lsan
on:
  workflow_call:
jobs:
  build-file-lsan:
    runs-on: ubuntu-latest
    name: lsan.supp
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/sanitize/config
      - name: Cache
        id: cache
        uses: actions/cache@v4
        with:
          path: ${{env.LSAN_DIR}}
          key: cache-lsan-suppression-file
      - name: Setup
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p ${{env.LSAN_DIR}}
          cat << EOF > ${{env.LSAN_DIR}}/${{env.LSAN_FILE}}
          leak:libevent_core-2.1.so
          leak:ompi_mpi_finalize
          leak:ompi_mpi_init
          leak:PMPI_Init
          leak:strdup
          EOF
