name: build-metis

on:
  workflow_call:

#############
# Build METIS
# Cache: ${{runner.os}}-build-${{env.METIS_DIR}}-v2.5
jobs:
  build-metis:
    runs-on: ubuntu-latest
    name: 4.0.3
    env:
      METIS_DIR: metis-${{inputs.METIS_VER}}
      METIS_TGZ: metis-${{inputs.METIS_VER}}.tar.gz
    steps:
      - uses: actions/checkout@v4
      - name: Env
        uses: ./.github/actions/sanitize/env
        with:
          parallel: 'true'
      - name: Cache
        id: cache
        uses: actions/cache@v4
        with:
          path: ${{env.METIS_DIR}}
          key: ${{runner.os}}-build-${{env.METIS_DIR}}-v2.5
      - name: Setup
        if: steps.cache.outputs.cache-hit != 'true'
        uses: ./.github/actions/sanitize/mpi
      - name: Build
        if: steps.cache.outputs.cache-hit != 'true'
        uses: mfem/github-actions/build-metis@v2.5
        with:
          archive: ${{env.METIS_TGZ}}
          dir: ${{env.METIS_DIR}}