name: test-seq-check

on:
  workflow_call:

###################
# Check MFEM Serial
jobs:
  test-seq-check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        sanitizer: [asan, msan, ubsan]
        
    name: ${{matrix.sanitizer}}

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/sanitize/env

      - name: Restore
        uses: ./.github/actions/sanitize/restore
        id: restore
        with:
          cache-path: mfem/build/examples/ex1
          cache-key: check-seq-${{matrix.sanitizer}}
          artifact-name: mfem-seq-${{matrix.sanitizer}}
          par: false

      - name: MFEM Check
        if: ${{ steps.restore.outputs.cache-hit != 'true' }}
        working-directory: mfem/build
        run: ninja -v check