name: test-par-check

on:
  workflow_call:

#####################
# Check MFEM Parallel
# Cache:   cache-check-par-${{matrix.sanitizer}}
# Upload: upload-check-par-${{matrix.sanitizer}}
jobs:
  test-par-check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        sanitizer: [asan, ubsan]
    name: ${{matrix.sanitizer}}
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/sanitize/env

      - uses: ./.github/actions/sanitize/mpi

      - uses: ./.github/actions/sanitize/restore
        with:
          cache-path: mfem/build/examples/ex1p
          cach-key: check-par-${{matrix.sanitizer}}
          artifact-name: mfem-par${{matrix.sanitizer}}
          par: true

      # - name: Cache
      #   if: ${{ env.DEBUG == 'true' }}
      #   id: cache
      #   uses: actions/cache@v4
      #   with:
      #     path: mfem/build/examples/ex1p
      #     key: cache-check-par-${{matrix.sanitizer}}
      # - name: Restore LLVM libcxx
      #   if: ${{ steps.cache.outputs.cache-hit != 'true' }}
      #   uses: actions/cache/restore@v4
      #   with:
      #     path: ${{env.LLVM_DIR}}
      #     fail-on-cache-miss: true
      #     key: cache-llvm-${{env.LLVM_VER}}-${{matrix.sanitizer}}
      # - name: Restore Hypre
      #   if: ${{ steps.cache.outputs.cache-hit != 'true' }}
      #   uses: actions/cache/restore@v4
      #   with:
      #     path: ${{env.HYPRE_DIR}}
      #     fail-on-cache-miss: true
      #     key: ${{runner.os}}-ompi-build-${{env.HYPRE_DIR}}-int32-fp64-v2.5
      # - name: Restore Metis
      #   if: ${{ steps.cache.outputs.cache-hit != 'true' }}
      #   uses: actions/cache/restore@v4
      #   with:
      #     path: ${{env.METIS_DIR}}
      #     fail-on-cache-miss: true
      #     key: ${{runner.os}}-build-${{env.METIS_DIR}}-v2.5
      # - name: Restore LSAN
      #   if: ${{ steps.cache.outputs.cache-hit != 'true' }}
      #   uses: actions/cache/restore@v4
      #   with:
      #     path: ${{env.LSAN_DIR}}
      #     fail-on-cache-miss: true
      #     key: cache-lsan-suppression-file
      # - name: Hypre/Metis links
      #   if: ${{ steps.cache.outputs.cache-hit != 'true' }}
      #   run: ln -s -f ${{env.HYPRE_DIR}} hypre && ln -s -f ${{env.METIS_DIR}} metis-4.0
      # - name: Checkout
      #   if: ${{ steps.cache.outputs.cache-hit != 'true' }}
      #   uses: actions/checkout@v4
      #   with:
      #     path: mfem
      #     ref: ubsan
      #     repository: mfem/mfem  # 🔥🔥🔥 Using MFEM/ubsan repository
      # - name: Download MFEM
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: upload-mfem-par-${{matrix.sanitizer}}
      #     path: mfem/build
      # - name: Ninja Patch
      #   if: ${{ steps.cache.outputs.cache-hit != 'true' }}
      #   working-directory: mfem/build
      #   run: sed -i -e 's/CXX_STATIC_LIBRARY_LINKER__mfem_Release.*/CUSTOM_COMMAND/' build.ninja
      - name: MFEM Check
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        working-directory: mfem/build
        run: ninja -v check