name: test-seq-unit-run

on:
  workflow_call:

######################################
# Unit tests MFEM Serial (Split & Run)
jobs:
  test-seq-unit:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        sanitizer: [asan, msan, ubsan]
        tag: [0, 1, 2, 3]

    name: ${{matrix.san}}-${{matrix.tag}}

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/sanitize/env

      - name: Restore
        id: restore
        uses: ./.github/actions/sanitize/restore
        with:
          no-cache: true
          artifact-name: mfem-seq-${{matrix.sanitizer}}

      - name: Restore Unit Tests
        uses: actions/download-artifact@v4
        with:
          name: upload-unit-seq-${{matrix.sanitizer}}
          path: mfem/build/tests/unit

      - name: Set Permissions
        run: find mfem/build/tests/unit -type f -exec chmod 755 {} \;

      - name: Split Unit Tests
        working-directory: mfem/build/tests/unit
        run: |
          ./unit_tests --list-test-names-only | tail -n +2 > list-test-names
          shuf list-test-names -o list-test-names
          split --verbose -n l/4 -d -a 1 list-test-names list-test-names-

      - name: Run Unit Tests ${{matrix.tag}}
        working-directory: mfem/build
        run: ${{env.CTEST}} tests/unit -V -R "unit_tests"