name: build-metis

on:
  workflow_call:
    inputs:
      METIS_VER:
        description: 'METIS version to build'
        required: false
        type: string
        default: '4.0.3'

#############
# Build METIS
# Cache: ${{runner.os}}-build-${{env.METIS_DIR}}-v2.5
jobs:
  build-metis:
    runs-on: ubuntu-latest
    name: ${{inputs.METIS_VER}}
    env:
      METIS_DIR: metis-${{inputs.METIS_VER}}
      METIS_TGZ: metis-${{inputs.METIS_VER}}.tar.gz
    steps:
      - name: Cache
        id: cache
        uses: actions/cache@v4
        with:
          path: ${{env.METIS_DIR}}
          key: ${{runner.os}}-build-${{env.METIS_DIR}}-v2.5
      - name: Setup
        if: steps.cache.outputs.cache-hit != 'true'
        run: sudo apt-get install openmpi-bin libopenmpi-dev
      - name: Build
        if: steps.cache.outputs.cache-hit != 'true'
        uses: mfem/github-actions/build-metis@v2.5
        with:
          archive: ${{env.METIS_TGZ}}
          dir: ${{env.METIS_DIR}}