---
name: "Sanitizers"

permissions:
  actions: write

on:
  # Run on pushes to main development branches
  push:
    branches: ["main"]
  # Run on all pull requests
  pull_request: 
  # Allow manual triggering for debugging
  workflow_dispatch:

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  build-mfem:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sanitizer: [asan, msan, ubsan]
        mpi: [par, seq]
    name: build-${{matrix.sanitizer}}-${{matrix.mpi}}
    steps:
      - name: Touch build-${{matrix.sanitizer}}-${{matrix.mpi}}
        run:  touch build-${{matrix.sanitizer}}-${{matrix.mpi}}
      - name: Cache
        uses: actions/cache@v4
        with:
          path: cache 
          key:  cache-build-${{matrix.sanitizer}}-${{matrix.mpi}}-${{github.sha}}

  build-hypre:
    runs-on: ubuntu-latest
    name: build-hypre
    steps:
      - name: Run build Hypre
        run: |
          echo Running build Hypre


  test:
    needs: [build-mfem, build-hypre]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sanitizer: [asan, msan, ubsan]
        test: [examples, miniapps, tests]
        mpi: [par, seq]
    name: test-${{matrix.sanitizer}}-${{matrix.mpi}}-${{matrix.test}}
    steps:
      - name: Restore
        uses: actions/cache@v4
        with:
          path: cache
          key:  cache-build-${{matrix.sanitizer}}-${{matrix.mpi}}-${{github.sha}}

      - name: Run ${{ matrix.test }}
        run: |
          echo Running ${{ matrix.test }}
