name: test-par-miniapps

on:
  workflow_call:

########################
# Miniapps MFEM Parallel
jobs:
  test-par-miniapps:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        sanitizer: [asan, ubsan]

    name: ${{matrix.sanitizer}}

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/sanitize/env
      
      - name: Restore
        id: restore
        uses: ./.github/actions/sanitize/restore
        with:
          cache-path: mfem/build/miniapps/meshing/pminimal-surface
          cache-key: miniapps-par-${{matrix.sanitizer}}
          artifact-name: mfem-par-${{matrix.sanitizer}}
          par: true

      - name: Build Miniapps
        if: ${{ steps.restore.outputs.cache-hit != 'true' }}
        working-directory: mfem/build
        run: ninja -v miniapps

      - name: Test Miniapps
        if: ${{ steps.restore.outputs.cache-hit != 'true' }}
        working-directory: mfem/build
        run: ${{env.CTEST}} miniapps