name: Sanitizers

permissions:
  actions: write

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  
  # Build steps for dependencies
  build-hypre:
    uses: ./.github/workflows/sanitize-build-hypre.yml
  
  build-metis:
    uses: ./.github/workflows/sanitize-build-metis.yml
  
  build-lsan:
    uses: ./.github/workflows/sanitize-build-lsan.yml
  
  build-libcxx:
    uses: ./.github/workflows/sanitize-build-libcxx.yml

  # Serial sanitizers: asan, msan, ubsan
  seq-asan:
    needs: [build-libcxx]
    uses: ./.github/workflows/sanitize.yml
    with:
      sanitizer: asan
  
  seq-msan:
    needs: [build-libcxx]
    uses: ./.github/workflows/sanitize.yml
    with:
      sanitizer: msan
  
  seq-ubsan:
    needs: [build-libcxx]
    uses: ./.github/workflows/sanitize.yml
    with:
      sanitizer: ubsan

  # Parallel sanitizers: asan, ubsan
  par-asan:
    needs: [build-libcxx, build-hypre, build-metis]
    uses: ./.github/workflows/sanitize.yml
    with:
      par: true  
      sanitizer: asan
  par-ubsan:
    needs: [build-libcxx, build-hypre, build-metis]
    uses: ./.github/workflows/sanitize.yml
    with:
      par: true
      sanitizer: ubsan