name: test-par-unit-run

on:
  workflow_call:

########################################
# Unit tests MFEM Parallel (Split & Run)
jobs:
  test-par-unit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sanitizer: [asan, ubsan]
        tag: [0, 1, 2, 3]

    name: ${{matrix.sanitizer}}-${{matrix.tag}}

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/sanitize/env
      - uses: ./.github/actions/sanitize/restore
        with:
          par: true
          no-cache: true
          artifact-name: mfem-par-${{matrix.sanitizer}}

      - name: Restore Unit Tests
        uses: actions/download-artifact@v4
        with:
          name: upload-unit-par-${{matrix.sanitizer}}
          path: mfem/build/tests/unit

      - name: Split Unit Tests
        working-directory: mfem/build/tests/unit
        run: |
          chmod 755 punit_tests
          ./punit_tests --list-test-names-only | tail -n +2 > list-test-names
          shuf list-test-names -o list-test-names
          split --verbose -n l/4 -d -a 1 list-test-names list-test-names-

      - name: Run Unit Tests ${{matrix.tag}}
        working-directory: mfem/build
        run: ${{env.CTEST}} tests/unit -V -R "punit_tests"
