name: all-in-one-seq
on:
  workflow_call:
jobs:
  build-seq:
    runs-on: ubuntu-latest
    name: build-seq
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/sanitize/mfem
        env:
          CXXFLAGS: ${{env.CXXFLAGS}} -fsanitize=address -fsanitize-address-use-after-scope
          LDFLAGS: ${{env.LDFLAGS}} -fsanitize=address
        with:
          key: mfem-seq-asan

  check-seq:
    needs: [build-seq]
    name: check-seq
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Restore
        uses: ./.github/actions/sanitize/restore
        id: restore
        with:
          cache-path: mfem/build/examples/ex1
          cache-key: check-seq-asan
          artifact-name: mfem-one-seq-asan
          par: false
      - name: MFEM Check
        if: ${{ steps.restore.outputs.cache-hit != 'true' }}
        working-directory: mfem/build
        run: ninja -v check
