name: test-par-check

on:
  workflow_call:

#####################
# Check MFEM Parallel
# Cache:   cache-check-par-${{matrix.sanitizer}}
# Upload: upload-check-par-${{matrix.sanitizer}}
jobs:
  test-par-check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        sanitizer: [asan, ubsan]
    name: ${{matrix.sanitizer}}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/sanitize/env
      - uses: ./.github/actions/sanitize/mpi
      - name: Restore
        id: cache
        uses: ./.github/actions/sanitize/restore
        with:
          cache-path: mfem/build/examples/ex1p
          cache-key: check-par-${{matrix.sanitizer}}
          artifact-name: mfem-par-${{matrix.sanitizer}}
          par: true
    
      - name: MFEM Check
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        working-directory: mfem/build
        run: ninja -v check