name: test-par-unit-miniapps

on:
  workflow_call:

###################################
# Tests Unit Miniapps MFEM Parallel
jobs:
  test-par-unit-miniapps:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        sanitizer: [asan, ubsan]

    name: ${{matrix.sanitizer}}
    
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/sanitize/env

      - name: Restore
        id: restore
        uses: ./.github/actions/sanitize/restore
        with:
          par: true
          no-cache: true
          artifact-name: mfem-par-${{matrix.sanitizer}}

      - name: Build Tests Unit Miniapps
        working-directory: mfem/build
        run: ninja -v tests/unit/all

      - name: Run Unit Tests Miniapps
        working-directory: mfem/build
        run: ${{env.CTEST}} tests/unit -E "unit_tests"