name: test-seq-unit-miniapps
on:
  workflow_call:
jobs:
  test-seq-unit-miniapps:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sanitizer: [asan, msan, ubsan]
    name: ${{matrix.sanitizer}}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/sanitize/restore
        with:
          build-key: mfem-seq-${{matrix.sanitizer}}
      - name: Build Tests Unit Miniapps
        working-directory: mfem/build
        run: ninja -v tests/unit/all
      - name: Run Tests Unit Miniapps
        working-directory: mfem/build
        run: ${{env.CTEST}} tests/unit -E "^unit_tests$|debug"
