name: build-mfem-par
on:
  workflow_call:
jobs:
  build-par-mfem:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sanitizer: [asan, ubsan]
        include:
          - sanitizer: asan
            cxxflags: "-fsanitize=address -fsanitize-address-use-after-scope"
            ldflags: "-fsanitize=address"
          - sanitizer: ubsan
            cxxflags: "-fsanitize=undefined"
            ldflags: "-fsanitize=undefined"
    name: ${{matrix.sanitizer}}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/sanitize/mfem
        with:
          key: mfem-par-${{matrix.sanitizer}}
          par: true
