name: build-mfem-seq

on:
  workflow_call:

###################
# Build MFEM Serial
jobs:
  build-seq-mfem:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        sanitizer: [asan, msan, ubsan]
        include:
          - sanitizer: asan
            cxxflags: "-fsanitize=address -fsanitize-address-use-after-scope"
            ldflags: "-fsanitize=address"
          - sanitizer: msan
            cxxflags: "-fsanitize=memory -fsanitize-memory-track-origins -fsanitize-memory-use-after-dtor"
            ldflags: "-fsanitize=memory"
          - sanitizer: ubsan
            cxxflags: "-fsanitize=undefined"
            ldflags: "-fsanitize=undefined"
    name: ${{matrix.sanitizer}}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/sanitize/env
      - uses: ./.github/actions/sanitize/mfem
        with:
          key: mfem-seq-${{matrix.sanitizer}}