name: test-seq-examples
on:
  workflow_call:
jobs:
  test-seq-examples:
    runs-on: ubuntu-latest    
    strategy:
      matrix:
        sanitizer: [asan, msan, ubsan]
    name: ${{matrix.sanitizer}}
    steps:
      - uses: actions/checkout@v4
      - name: Restore
        id: restore
        uses: ./.github/actions/sanitize/restore
        with:
          cache-path: mfem/build/examples/ex1
          cache-key: examples-seq-${{matrix.sanitizer}}
          build-key: mfem-seq-${{matrix.sanitizer}}
      - name: Build Examples
        if: ${{ steps.restore.outputs.cache-hit != 'true' }}
        working-directory: mfem/build
        run: ninja -v examples
      - name: Test Examples
        if: ${{ steps.restore.outputs.cache-hit != 'true' }}
        working-directory: mfem/build
        run: ${{env.CTEST}} examples
