name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up environment
        run: # Your setup commands (e.g., install Node.js, dependencies)
      - name: Build
        run: # Your build command
      - name: Cache build artifacts
        uses: actions/cache@v4
        with:
          path: # Path to build output (e.g., dist/, build/)
          key: build-${{ github.sha }}
  
  downstream:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task: [test, examples, miniapps]
    steps:
      - uses: actions/checkout@v4
      - name: Set up environment
        run: # Same setup as build job
      - name: Restore build artifacts
        uses: actions/cache@v4
        with:
          path: # Same path as build cache
          key: build-${{ github.sha }}
      - name: Run ${{ matrix.task }}
        run: # Command for each task (e.g., npm test, npm run examples)